[package]
name = "server"
version = "0.1.0"
authors = ["karim <k.elmougi@usherbrooke.ca>"]
edition = "2018"

[dependencies]
csv = "1.0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.39"
tiny_http = "0.6.2"
bincode = "1.1.2"
